"""
Single source of truth for what counts as "weak crypto."
Sourced from NIST SP 800-131A, FIPS 203/204/205, and RFC 8996.

Each entry has per-language pattern keys:
  python_pattern, java_pattern, js_pattern, go_pattern,
  c_pattern, kotlin_pattern, ruby_pattern, php_pattern,
  config_pattern (for .env/.yaml/.toml/.properties/Dockerfile)
"""

SIGNATURES = [
    # ── Hashing ─────────────────────────────────────────────────────────────
    {
        "id": "MD5",
        "algorithm": "MD5",
        "category": "hashing",
        "python_pattern": r"hashlib\.md5\(|Crypto\.Hash\.MD5|MD5\.new\(|hashes\.MD5\(",
        "java_pattern": r'MessageDigest\.getInstance\(\s*["\']MD5["\']\s*\)',
        "js_pattern": r"createHash\s*\(\s*['\"]md5['\"]\s*\)|crypto\.createHash\(['\"]md5['\"]\)",
        "go_pattern": r'md5\.New\(\)|"crypto/md5"',
        "c_pattern": r"MD5_Init\s*\(|MD5\s*\(|EVP_md5\s*\(",
        "kotlin_pattern": r'MessageDigest\.getInstance\(\s*["\']MD5["\']\s*\)',
        "ruby_pattern": r"Digest::MD5\b|OpenSSL::Digest::MD5\b",
        "php_pattern": r"md5\s*\(|hash\s*\(\s*['\"]md5['\"]\s*,",
        "config_pattern": r"(?i)algorithm\s*[=:]\s*['\"]?md5['\"]?|HASH\s*[=:]\s*['\"]?md5['\"]?",
        "description": "MD5 hash algorithm is collision-vulnerable and deprecated by NIST.",
    },
    {
        "id": "SHA1",
        "algorithm": "SHA1",
        "category": "hashing",
        "python_pattern": r"hashlib\.sha1\(|Crypto\.Hash\.SHA1|SHA1\.new\(|hashes\.SHA1\(",
        "java_pattern": r'MessageDigest\.getInstance\(\s*["\']SHA-?1["\']\s*\)',
        "js_pattern": r"createHash\s*\(\s*['\"]sha1['\"]\s*\)|crypto\.createHash\(['\"]sha1['\"]\)",
        "go_pattern": r'sha1\.New\(\)|"crypto/sha1"',
        "c_pattern": r"SHA1_Init\s*\(|SHA1\s*\(|EVP_sha1\s*\(",
        "kotlin_pattern": r'MessageDigest\.getInstance\(\s*["\']SHA-?1["\']\s*\)',
        "ruby_pattern": r"Digest::SHA1\b|OpenSSL::Digest::SHA1\b",
        "php_pattern": r"sha1\s*\(|hash\s*\(\s*['\"]sha1['\"]\s*,",
        "config_pattern": r"(?i)algorithm\s*[=:]\s*['\"]?sha-?1['\"]?",
        "description": "SHA-1 is vulnerable to collision attacks and deprecated by NIST.",
    },
    {
        "id": "MD2_MD4",
        "algorithm": "MD2/MD4",
        "category": "hashing",
        "python_pattern": r"hashlib\.(?:md2|md4)\(|Crypto\.Hash\.(?:MD2|MD4)|(?:MD2|MD4)\.new\(",
        "java_pattern": r'MessageDigest\.getInstance\(\s*["\']MD[24]["\']\s*\)',
        "js_pattern": r"createHash\s*\(\s*['\"]md[24]['\"]\s*\)",
        "go_pattern": r'"golang.org/x/crypto/md4"',
        "c_pattern": r"MD2_Init\s*\(|MD4_Init\s*\(|EVP_md2\s*\(|EVP_md4\s*\(",
        "kotlin_pattern": r'MessageDigest\.getInstance\(\s*["\']MD[24]["\']\s*\)',
        "ruby_pattern": r"Digest::MD4\b|OpenSSL::Digest::MD4\b",
        "php_pattern": r"hash\s*\(\s*['\"]md[24]['\"]\s*,",
        "config_pattern": r"(?i)algorithm\s*[=:]\s*['\"]?md[24]['\"]?",
        "description": "MD2 and MD4 are obsolete, collision-vulnerable hash algorithms.",
    },
    {
        "id": "RIPEMD160",
        "algorithm": "RIPEMD-160",
        "category": "hashing",
        "python_pattern": r"Crypto\.Hash\.RIPEMD160|RIPEMD160\.new\(|hashes\.RIPEMD160\(",
        "java_pattern": r'MessageDigest\.getInstance\(\s*["\']RIPEMD(?:-?160)?["\']\s*\)',
        "js_pattern": r"createHash\s*\(\s*['\"]ripemd160['\"]\s*\)",
        "go_pattern": r'"golang.org/x/crypto/ripemd160"',
        "c_pattern": r"RIPEMD160_Init\s*\(|EVP_ripemd160\s*\(",
        "kotlin_pattern": r'MessageDigest\.getInstance\(\s*["\']RIPEMD(?:-?160)?["\']\s*\)',
        "ruby_pattern": r"Digest::RMD160\b|OpenSSL::Digest::RIPEMD160\b",
        "php_pattern": r"hash\s*\(\s*['\"]ripemd160['\"]\s*,",
        "config_pattern": r"(?i)algorithm\s*[=:]\s*['\"]?ripemd-?160['\"]?",
        "description": "RIPEMD-160 is below current collision-resistance recommendations.",
    },
    # ── Symmetric Ciphers ───────────────────────────────────────────────────
    {
        "id": "DES",
        "algorithm": "DES",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.DES\b|DES\.new\(|algorithms\.DES\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']DES(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]des['\"]|createDecipheriv\s*\(\s*['\"]des['\"]",
        "go_pattern": r'des\.NewCipher\(|"crypto/des"',
        "c_pattern": r"DES_set_key\s*\(|DES_ecb_encrypt\s*\(|EVP_des_\w+\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']DES(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]DES['\"]|cipher\.name.*DES",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]des['\"]|mcrypt_encrypt.*MCRYPT_DES",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?des['\"]?|algorithm\s*[=:]\s*['\"]?des['\"]?",
        "description": "DES features a 56-bit key size and is vulnerable to brute-force attacks.",
    },
    {
        "id": "3DES",
        "algorithm": "3DES",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.DES3|DES3\.new\(|algorithms\.TripleDES\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\'](?:DESede|TripleDES)(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]des-ede|createCipheriv\s*\(\s*['\"]des3",
        "go_pattern": r'des\.NewTripleDESCipher\(',
        "c_pattern": r"EVP_des_ede3\w*\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\'](?:DESede|TripleDES)(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]DES-EDE3['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]des-ede3",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?(?:3des|desede|tripledes)['\"]?",
        "description": "Triple DES (3DES) is vulnerable to Sweet32 attack and deprecated by NIST.",
    },
    {
        "id": "RC4",
        "algorithm": "RC4",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.ARC4|ARC4\.new\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\'](?:RC4|ARCFOUR)(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]rc4",
        "go_pattern": r'rc4\.NewCipher\(|"crypto/rc4"',
        "c_pattern": r"RC4\s*\(|RC4_set_key\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']RC4["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]RC4['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]rc4",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?rc4['\"]?",
        "description": "RC4 stream cipher suffers from bias in output byte stream.",
    },
    {
        "id": "BLOWFISH",
        "algorithm": "Blowfish",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.Blowfish|Blowfish\.new\(|algorithms\.Blowfish\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']Blowfish(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]bf['\"]|createCipheriv\s*\(\s*['\"]blowfish['\"]",
        "go_pattern": r'"golang.org/x/crypto/blowfish"',
        "c_pattern": r"BF_set_key\s*\(|BF_ecb_encrypt\s*\(|EVP_bf_ecb\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']Blowfish(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]BF['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]bf",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?blowfish['\"]?",
        "description": "Blowfish has a 64-bit block size and is unsuitable for modern secure systems.",
    },
    {
        "id": "CAST5",
        "algorithm": "CAST5",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.CAST|CAST\.new\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']CAST5(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]cast['\"]",
        "go_pattern": r'"golang.org/x/crypto/cast5"',
        "c_pattern": r"CAST_set_key\s*\(|EVP_cast5_\w+\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']CAST5(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]CAST5['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]cast5",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?cast5?['\"]?",
        "description": "CAST5 is legacy cryptography with a 64-bit block size.",
    },
    {
        "id": "IDEA",
        "algorithm": "IDEA",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.IDEA|IDEA\.new\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']IDEA(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]idea['\"]",
        "go_pattern": r'idea\.NewCipher\(',
        "c_pattern": r"IDEA_set_encrypt_key\s*\(|EVP_idea_\w+\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']IDEA(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]IDEA['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]idea",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?idea['\"]?",
        "description": "IDEA is legacy cryptography and should be replaced in modern systems.",
    },
    {
        "id": "RC2",
        "algorithm": "RC2",
        "category": "symmetric",
        "python_pattern": r"Crypto\.Cipher\.ARC2|ARC2\.new\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']RC2(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]rc2",
        "go_pattern": r'rc2\.NewCipher\(',
        "c_pattern": r"RC2_set_key\s*\(|EVP_rc2_\w+\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']RC2(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]RC2['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]rc2",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?rc2['\"]?",
        "description": "RC2 is a legacy cipher with limited effective key strength.",
    },
    {
        "id": "AES_ECB",
        "algorithm": "AES-ECB",
        "category": "symmetric",
        "python_pattern": r"AES\.MODE_ECB|modes\.ECB\(|AES\.new\s*\([^,]+,\s*AES\.MODE_ECB\b",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']AES/ECB(?:/[^"\']*)?["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]aes-\d+-ecb['\"]",
        "go_pattern": r"aes\.NewCipher.*ECB|NewECBEncrypter\s*\(",
        "c_pattern": r"EVP_aes_\d+_ecb\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']AES/ECB(?:/[^"\']*)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]AES-\d+-ECB['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]aes-\d+-ecb",
        "config_pattern": r"(?i)(?:cipher|mode)\s*[=:]\s*['\"]?(?:aes[-/]?ecb|ECB)['\"]?",
        "description": "ECB mode reveals plaintext patterns and provides no semantic security.",
    },
    {
        "id": "NULL_CIPHER",
        "algorithm": "NULL cipher",
        "category": "symmetric",
        "python_pattern": r"(?:NullCipher|NoEncryption)\(|(?:xor|XOR)\.(?:encrypt|decrypt)\(",
        "java_pattern": r'Cipher\.getInstance\(\s*["\'](?:NULL|NONE)["\']\s*\)',
        "js_pattern": r"createCipheriv\s*\(\s*['\"]null",
        "go_pattern": r"tls\.CipherSuite.*NULL",
        "c_pattern": r"EVP_enc_null\s*\(",
        "kotlin_pattern": r'Cipher\.getInstance\(\s*["\']NULL["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Cipher['\"]NULL['\"]",
        "php_pattern": r"openssl_encrypt\s*\([^,]+,\s*['\"]null",
        "config_pattern": r"(?i)cipher\s*[=:]\s*['\"]?null['\"]?",
        "description": "A null or no-encryption cipher provides no confidentiality.",
    },
    {
        "id": "PBE_WEAK",
        "algorithm": "Weak PBE",
        "category": "password_kdf",
        "python_pattern": r"(?:PBKDF2HMAC|PBKDF2)(?:[^\n]*hashes\.SHA1|[^\n]*hashlib\.sha1)",
        "java_pattern": r'Cipher\.getInstance\(\s*["\']PBEWith(?:MD5|SHA1)(?:And(?:DES|DESede|3DES))?["\']\s*\)|SecretKeyFactory\.getInstance\(\s*["\']PBKDF2WithHmacSHA1["\']\s*\)',
        "js_pattern": r"pbkdf2Sync\s*\([^,]+,[^,]+,[^,]+,[^,]+,\s*['\"]sha1['\"]",
        "go_pattern": r"pbkdf2\.Key\([^,]+,[^,]+,[^,]+,[^,]+,\s*sha1\.New",
        "c_pattern": r"PKCS5_PBEKEYGEN|PKCS5_PBKDF2_HMAC_SHA1",
        "kotlin_pattern": r'SecretKeyFactory\.getInstance\(\s*["\']PBKDF2WithHmacSHA1["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKCS5\.pbkdf2_hmac_sha1",
        "php_pattern": r"hash_pbkdf2\s*\(\s*['\"]sha1['\"]",
        "config_pattern": r"(?i)kdf\s*[=:]\s*['\"]?pbkdf2[-_]sha1['\"]?",
        "description": "Legacy password-based encryption or SHA-1 KDFs need migration to modern authenticated encryption and KDF parameters.",
    },
    # ── Asymmetric Encryption & Signatures ────────────────────────────────────
    {
        "id": "RSA",
        "algorithm": "RSA",
        "category": "asymmetric",
        "python_pattern": r"RSA\.generate\(|rsa\.newkeys\(|rsa\.generate_private_key\(",
        "java_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']RSA["\']\s*\)',
        "js_pattern": r"generateKeyPair\s*\(\s*['\"]rsa['\"]|generateKeyPairSync\s*\(\s*['\"]rsa['\"]",
        "go_pattern": r"rsa\.GenerateKey\s*\(|\"crypto/rsa\"",
        "c_pattern": r"RSA_generate_key\s*\(|RSA_generate_key_ex\s*\(|EVP_PKEY_CTX_set_rsa_keygen_bits\s*\(",
        "kotlin_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']RSA["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::RSA\.new\s*\(\s*(?:512|1024)\s*\)|OpenSSL::PKey::RSA\.generate\s*\(\s*(?:512|1024)\s*\)",
        "php_pattern": r"openssl_pkey_new.*rsa_key_bits.*(?:512|1024)|OPENSSL_KEYTYPE_RSA",
        "config_pattern": r"(?i)key_?(?:type|algo)\s*[=:]\s*['\"]?rsa['\"]?",
        "description": "RSA algorithm is vulnerable to Shor's algorithm on quantum computers.",
    },
    {
        "id": "ECDSA",
        "algorithm": "ECDSA",
        "category": "asymmetric",
        "python_pattern": r"ECC\.generate\(|ec\.generate_private_key\(|secp192r1|secp160r1|prime192v1",
        "java_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']EC(?:DSA)?["\']\s*\)|secp192r1|secp160r1|prime192v1',
        "js_pattern": r"generateKeyPair\s*\(\s*['\"]ec['\"]|generateKeyPairSync\s*\(\s*['\"]ec['\"]",
        "go_pattern": r"ecdsa\.GenerateKey\s*\(|elliptic\.P224\(\)|\"crypto/ecdsa\"",
        "c_pattern": r"EC_KEY_new_by_curve_name\s*\(|EVP_PKEY_EC\b",
        "kotlin_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']EC(?:DSA)?["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::EC\.new\s*\(['\"]prime192v1['\"]|OpenSSL::PKey::EC\.new\s*\(['\"]secp160",
        "php_pattern": r"OPENSSL_KEYTYPE_EC",
        "config_pattern": r"(?i)curve\s*[=:]\s*['\"]?(?:secp192|secp160|prime192)['\"]?",
        "description": "ECDSA curves are vulnerable to Shor's algorithm on quantum computers.",
    },
    {
        "id": "DSA",
        "algorithm": "DSA",
        "category": "asymmetric",
        "python_pattern": r"DSA\.generate\(|dsa\.generate_private_key\(",
        "java_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']DSA["\']\s*\)',
        "js_pattern": r"generateKeyPair\s*\(\s*['\"]dsa['\"]",
        "go_pattern": r"dsa\.GenerateParameters\s*\(|\"crypto/dsa\"",
        "c_pattern": r"DSA_generate_parameters_ex\s*\(|DSA_generate_key\s*\(",
        "kotlin_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']DSA["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::DSA\.generate\b",
        "php_pattern": r"OPENSSL_KEYTYPE_DSA",
        "config_pattern": r"(?i)key_?type\s*[=:]\s*['\"]?dsa['\"]?",
        "description": "DSA is legacy public-key cryptography and is vulnerable to quantum attacks.",
    },
    {
        "id": "ELGAMAL",
        "algorithm": "ElGamal",
        "category": "asymmetric",
        "python_pattern": r"Crypto\.PublicKey\.ElGamal|ElGamal\.generate\(",
        "java_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']ElGamal["\']\s*\)',
        "js_pattern": r"createElGamal\s*\(",
        "go_pattern": r'"golang.org/x/crypto/openpgp/elgamal"',
        "c_pattern": r"ElGamal_generate_key\s*\(",
        "kotlin_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']ElGamal["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::ElGamal",
        "php_pattern": r"elgamal_generate",
        "config_pattern": r"(?i)key_?type\s*[=:]\s*['\"]?elgamal['\"]?",
        "description": "ElGamal is classical public-key cryptography and requires a quantum-safe migration plan.",
    },
    {
        "id": "ED25519_ED448",
        "algorithm": "Ed25519/Ed448",
        "category": "asymmetric",
        "python_pattern": r"(?:ed25519|ed448)\.(?:Ed25519PrivateKey|Ed448PrivateKey|generate|sign)",
        "java_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']Ed(?:25519|448)["\']\s*\)|Signature\.getInstance\(\s*["\']Ed(?:25519|448)["\']\s*\)',
        "js_pattern": r"generateKeyPair\s*\(\s*['\"]ed25519['\"]|generateKeyPair\s*\(\s*['\"]ed448['\"]",
        "go_pattern": r'"crypto/ed25519"',
        "c_pattern": r"EVP_PKEY_ED25519\b|EVP_PKEY_ED448\b",
        "kotlin_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']Ed25519["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::ED25519",
        "php_pattern": r"sodium_crypto_sign",
        "config_pattern": r"(?i)key_?type\s*[=:]\s*['\"]?ed25519['\"]?",
        "description": "Ed25519 and Ed448 are vulnerable to sufficiently capable quantum attacks and need a PQC transition plan.",
    },
    {
        "id": "ECDH_X25519",
        "algorithm": "ECDH/X25519",
        "category": "key_exchange",
        "python_pattern": r"(?:x25519|x448)\.(?:X25519PrivateKey|X448PrivateKey|generate|derive)[^\n]*|ec\.ECDH\(",
        "java_pattern": r'KeyAgreement\.getInstance\(\s*["\'](?:ECDH|X25519|X448)["\']\s*\)|KeyPairGenerator\.getInstance\(\s*["\'](?:EC|X25519|X448)["\']\s*\)',
        "js_pattern": r"createECDH\s*\(|generateKeyPair\s*\(\s*['\"]x25519['\"]",
        "go_pattern": r'"golang.org/x/crypto/curve25519"|"crypto/ecdh"',
        "c_pattern": r"EVP_PKEY_X25519\b|EVP_PKEY_X448\b",
        "kotlin_pattern": r'KeyAgreement\.getInstance\(\s*["\']X25519["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::X25519",
        "php_pattern": r"sodium_crypto_box",
        "config_pattern": r"(?i)key_?exchange\s*[=:]\s*['\"]?x25519['\"]?",
        "description": "Classical elliptic-curve key exchange is vulnerable to Shor's algorithm and should transition to hybrid ML-KEM.",
    },
    {
        "id": "WEAK_SIGNATURE",
        "algorithm": "Weak signature",
        "category": "signature",
        "python_pattern": r"(?:pkcs1_15|pss)\.new[^\n]*\.sign[^\n]*(?:MD5|SHA1)",
        "java_pattern": r'Signature\.getInstance\(\s*["\'](?:MD5withRSA|SHA1withRSA|SHA1withDSA|NONEwithRSA)["\']\s*\)',
        "js_pattern": r"createSign\s*\(\s*['\"]RSA-MD5['\"]|createSign\s*\(\s*['\"]RSA-SHA1['\"]",
        "go_pattern": r"rsa\.SignPKCS1v15.*crypto\.SHA1",
        "c_pattern": r"RSA_sign\s*\(\s*NID_md5|RSA_sign\s*\(\s*NID_sha1",
        "kotlin_pattern": r'Signature\.getInstance\(\s*["\']SHA1withRSA["\']\s*\)',
        "ruby_pattern": r"OpenSSL::Digest::SHA1\.new.*sign",
        "php_pattern": r"openssl_sign\s*\([^,]+,[^,]+,[^,]+,\s*OPENSSL_ALGO_SHA1",
        "config_pattern": r"(?i)signature_?algo\s*[=:]\s*['\"]?sha1withrsa['\"]?",
        "description": "Legacy or raw signature constructions are vulnerable to collisions, misuse, or quantum attacks.",
    },
    # ── TLS / SSL Protocols ──────────────────────────────────────────────────
    {
        "id": "SSLv3_TLS10_11",
        "algorithm": "TLS 1.0/1.1",
        "category": "protocol",
        "python_pattern": r"ssl\.PROTOCOL_(?:SSLv2|SSLv3|SSLv23|TLSv1|TLSv1_1)|minimum_version\s*=\s*ssl\.TLSVersion\.TLSv1(?:\.1)?",
        "java_pattern": r'SSLContext\.getInstance\(\s*["\'](?:SSL|SSLv2|SSLv3|TLSv1|TLSv1\.1|DTLSv1\.0)["\']\s*\)|setEnabledProtocols\([^\n]*["\'](?:SSLv2|SSLv3|TLSv1|TLSv1\.1)["\']',
        "js_pattern": r"secureProtocol\s*:\s*['\"](?:SSLv3|TLSv1|TLSv1_method|TLSv1_1)['\"]|minVersion\s*:\s*['\"]TLSv1(?:\.1)?['\"]",
        "go_pattern": r"tls\.VersionTLS10\b|tls\.VersionTLS11\b|MinVersion:\s*tls\.VersionTLS1[01]",
        "c_pattern": r"TLSv1_method\s*\(|TLSv1_1_method\s*\(|SSLv3_method\s*\(|SSL_CTX_new\s*\(\s*TLSv1",
        "kotlin_pattern": r'SSLContext\.getInstance\(\s*["\'](?:TLSv1|TLSv1\.1)["\']\s*\)',
        "ruby_pattern": r"ssl_version\s*=\s*['\"](?:SSLv3|TLSv1|TLSv1_1)['\"]|OpenSSL::SSL::TLS1_VERSION\b",
        "php_pattern": r"STREAM_CRYPTO_METHOD_TLS(?:v1_0|v1_1)|CURL_SSLVERSION_TLSv1_[01]\b",
        "config_pattern": r"(?i)ssl_?protocol\s*[=:]\s*['\"]?(?:sslv3|tlsv1(?:\.1)?)['\"]?|min_?tls_?version\s*[=:]\s*['\"]?1\.[01]['\"]?",
        "description": "Deprecated TLS/SSL protocol versions vulnerable to POODLE, BEAST attacks.",
    },
    # ── Key Exchange ─────────────────────────────────────────────────────────
    {
        "id": "STATIC_DH",
        "algorithm": "Static DH",
        "category": "key_exchange",
        "python_pattern": r"DH\.generate\(|DiffieHellman\(",
        "java_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']DH["\']\s*\)|["\']DiffieHellman["\']',
        "js_pattern": r"createDiffieHellman\s*\(|getDiffieHellman\s*\(",
        "go_pattern": r'"golang.org/x/crypto/dh"',
        "c_pattern": r"DH_new\s*\(|DH_generate_parameters\s*\(|EVP_PKEY_DH\b",
        "kotlin_pattern": r'KeyPairGenerator\.getInstance\(\s*["\']DH["\']\s*\)',
        "ruby_pattern": r"OpenSSL::PKey::DH\.new\b",
        "php_pattern": r"OPENSSL_KEYTYPE_DH",
        "config_pattern": r"(?i)key_?exchange\s*[=:]\s*['\"]?(?:dh|diffie.hellman)['\"]?",
        "description": "Static Diffie-Hellman lacks perfect forward secrecy and quantum resistance.",
    },
]
